namespace CopilotTest.Models;

/// <summary>One spell in the built-in spell library.</summary>
public record LibrarySpell(
    string Name,
    int Level,
    string School,
    string[] Classes,
    string CastingTime,
    string Range,
    string Components,
    string Duration,
    bool Concentration,
    bool Ritual,
    string Description,
    string Source = "PHB 2024"
);

/// <summary>
/// Offline SRD 5e spell library (levels 0-5) — no network required.
/// Used by the level-up wizard and the character sheet spell picker.
/// </summary>
public static class SpellLibrary
{
    public static bool ClassCanCast(string characterClass) =>
        ClassKey(characterClass) is not "";

    /// <summary>Normalizes a class name to the keys used in spell Classes arrays.</summary>
    public static string ClassKey(string characterClass) => characterClass.Trim().ToLowerInvariant() switch
    {
        "bard" => "bard", "cleric" => "cleric", "druid" => "druid",
        "paladin" => "paladin", "ranger" => "ranger", "sorcerer" => "sorcerer",
        "warlock" => "warlock", "wizard" => "wizard",
        _ => "",
    };

    /// <summary>Max spell level a class can cast at a given character level.</summary>
    public static int MaxSpellLevel(string characterClass, int level) =>
        LevelUpRules.SlotsForLevel(characterClass, level) is { Count: > 0 } slots ? slots.Max(s => s.Level) : 0;

    public static List<LibrarySpell> Search(string? query, string? characterClass, int maxLevel, int? exactLevel = null)
    {
        var key = string.IsNullOrWhiteSpace(characterClass) ? "" : ClassKey(characterClass);
        return All
            .Where(s => s.Level <= maxLevel)
            .Where(s => exactLevel == null || s.Level == exactLevel)
            .Where(s => key == "" || s.Classes.Contains(key))
            .Where(s => string.IsNullOrWhiteSpace(query) || s.Name.Contains(query, StringComparison.OrdinalIgnoreCase))
            .OrderBy(s => s.Level).ThenBy(s => s.Name)
            .ToList();
    }

    public static Spell ToSpell(LibrarySpell s, Guid characterId) => new()
    {
        CharacterId   = characterId,
        Name          = s.Name,
        Level         = s.Level,
        School        = s.School,
        CastingTime   = s.CastingTime,
        Range         = s.Range,
        Components    = s.Components,
        Duration      = s.Duration,
        Concentration = s.Concentration,
        IsRitual      = s.Ritual,
        IsPrepared    = true,
        Description   = s.Description,
    };

    // Class key shorthands
    private static readonly string[] BD  = ["bard"];
    private static readonly string[] CL  = ["cleric"];
    private static readonly string[] DR  = ["druid"];
    private static readonly string[] SW  = ["sorcerer", "wizard"];
    private static readonly string[] SWW = ["sorcerer", "warlock", "wizard"];
    private static readonly string[] PAL = ["paladin"];

    public static readonly List<LibrarySpell> All =
    [
        // ── Cantrips ─────────────────────────────────────────────────────────
        new("Acid Splash", 0, "Conjuration", SW, "1 action", "60 ft", "V, S", "Instantaneous", false, false,
            "Hurl a bubble of acid at one or two creatures within 5 ft of each other. DEX save or take 1d6 acid damage (2d6 at level 5)."),
        new("Blade Ward", 0, "Abjuration", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "Self", "V, S", "1 round", false, false,
            "Until your next turn, you have resistance against bludgeoning, piercing, and slashing damage from weapon attacks."),
        new("Chill Touch", 0, "Necromancy", SWW, "1 action", "120 ft", "V, S", "1 round", false, false,
            "Ranged spell attack for 1d8 necrotic (2d8 at level 5); the target can't regain HP until your next turn. Undead get disadvantage vs you."),
        new("Dancing Lights", 0, "Evocation", ["bard", "sorcerer", "wizard"], "1 action", "120 ft", "V, S, M", "1 min", true, false,
            "Create up to four hovering lights you can move as a bonus action."),
        new("Druidcraft", 0, "Transmutation", DR, "1 action", "30 ft", "V, S", "Instantaneous", false, false,
            "Whisper to the spirits of nature: predict weather, bloom a flower, snuff a small flame, or make a tiny sensory effect."),
        new("Eldritch Blast", 0, "Evocation", ["warlock"], "1 action", "120 ft", "V, S", "Instantaneous", false, false,
            "Ranged spell attack for 1d10 force damage. Fires two beams at level 5 (separate targets allowed)."),
        new("Fire Bolt", 0, "Evocation", SW, "1 action", "120 ft", "V, S", "Instantaneous", false, false,
            "Ranged spell attack for 1d10 fire damage (2d10 at level 5). Ignites flammable objects."),
        new("Guidance", 0, "Divination", ["cleric", "druid"], "1 action", "Touch", "V, S", "1 min", true, false,
            "Touched creature adds 1d4 to one ability check of its choice before the spell ends."),
        new("Light", 0, "Evocation", ["bard", "cleric", "sorcerer", "wizard"], "1 action", "Touch", "V, M", "1 hour", false, false,
            "An object you touch sheds bright light in a 20-ft radius and dim light 20 ft beyond."),
        new("Mage Hand", 0, "Conjuration", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "30 ft", "V, S", "1 min", false, false,
            "A spectral hand manipulates objects, opens doors, or carries up to 10 pounds."),
        new("Mending", 0, "Transmutation", ["bard", "cleric", "druid", "sorcerer", "wizard"], "1 minute", "Touch", "V, S, M", "Instantaneous", false, false,
            "Repair a single break or tear in an object you touch."),
        new("Message", 0, "Transmutation", ["bard", "sorcerer", "wizard"], "1 action", "120 ft", "V, S, M", "1 round", false, false,
            "Whisper a message to a creature within range; only it hears, and it can whisper back."),
        new("Minor Illusion", 0, "Illusion", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "30 ft", "S, M", "1 min", false, false,
            "Create a sound or a stationary image no larger than a 5-ft cube. INT (Investigation) check vs your DC to see through it."),
        new("Poison Spray", 0, "Conjuration", ["druid", "sorcerer", "warlock", "wizard"], "1 action", "10 ft", "V, S", "Instantaneous", false, false,
            "A puff of noxious gas: CON save or take 1d12 poison damage (2d12 at level 5)."),
        new("Prestidigitation", 0, "Transmutation", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "10 ft", "V, S", "Up to 1 hour", false, false,
            "Minor magical trick: spark, clean, soil, chill, warm, flavor, or a small trinket or illusion."),
        new("Produce Flame", 0, "Conjuration", DR, "1 action", "Self", "V, S", "10 min", false, false,
            "A flame in your palm sheds light; hurl it as a ranged spell attack for 1d8 fire damage (2d8 at level 5)."),
        new("Ray of Frost", 0, "Evocation", SW, "1 action", "60 ft", "V, S", "Instantaneous", false, false,
            "Ranged spell attack for 1d8 cold damage (2d8 at level 5); target's speed is reduced by 10 ft until your next turn."),
        new("Resistance", 0, "Abjuration", ["cleric", "druid"], "1 action", "Touch", "V, S, M", "1 min", true, false,
            "Touched creature adds 1d4 to one saving throw of its choice before the spell ends."),
        new("Sacred Flame", 0, "Evocation", CL, "1 action", "60 ft", "V, S", "Instantaneous", false, false,
            "Flame-like radiance descends: DEX save or take 1d8 radiant damage (2d8 at level 5). Cover gives no benefit."),
        new("Shillelagh", 0, "Transmutation", DR, "1 bonus action", "Touch", "V, S, M", "1 min", false, false,
            "Your club or quarterstaff uses your spellcasting ability for attack/damage and deals 1d8 damage."),
        new("Shocking Grasp", 0, "Evocation", SW, "1 action", "Touch", "V, S", "Instantaneous", false, false,
            "Melee spell attack for 1d8 lightning (2d8 at level 5); advantage if target wears metal armor; target can't take reactions."),
        new("Spare the Dying", 0, "Necromancy", CL, "1 action", "Touch", "V, S", "Instantaneous", false, false,
            "A creature at 0 HP becomes stable."),
        new("Thaumaturgy", 0, "Transmutation", CL, "1 action", "30 ft", "V", "Up to 1 min", false, false,
            "Minor divine wonder: booming voice, flickering flames, tremors, slamming doors, or glowing eyes."),
        new("Thorn Whip", 0, "Transmutation", DR, "1 action", "30 ft", "V, S, M", "Instantaneous", false, false,
            "Melee spell attack with a vine whip: 1d6 piercing (2d6 at level 5) and pull a Large or smaller creature 10 ft closer."),
        new("True Strike", 0, "Divination", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "30 ft", "S", "1 round", true, false,
            "You gain advantage on your first attack roll against the target on your next turn."),
        new("Vicious Mockery", 0, "Enchantment", BD, "1 action", "60 ft", "V", "Instantaneous", false, false,
            "Insult laced with enchantment: WIS save or take 1d4 psychic damage (2d4 at level 5) and disadvantage on its next attack roll."),

        // ── Level 1 ──────────────────────────────────────────────────────────
        new("Animal Friendship", 1, "Enchantment", ["bard", "druid", "ranger"], "1 action", "30 ft", "V, S, M", "24 hours", false, false,
            "Convince a beast (INT 3 or less) you mean no harm: WIS save or charmed for the duration."),
        new("Bane", 1, "Enchantment", ["bard", "cleric"], "1 action", "30 ft", "V, S, M", "1 min", true, false,
            "Up to three creatures make a CHA save or subtract 1d4 from their attack rolls and saving throws."),
        new("Bless", 1, "Enchantment", ["cleric", "paladin"], "1 action", "30 ft", "V, S, M", "1 min", true, false,
            "Up to three creatures add 1d4 to their attack rolls and saving throws. One of the best support spells in the game."),
        new("Burning Hands", 1, "Evocation", SW, "1 action", "Self (15-ft cone)", "V, S", "Instantaneous", false, false,
            "Flames shoot from your fingertips: each creature in a 15-ft cone makes a DEX save, taking 3d6 fire damage on a fail (half on success)."),
        new("Charm Person", 1, "Enchantment", ["bard", "druid", "sorcerer", "warlock", "wizard"], "1 action", "30 ft", "V, S", "1 hour", false, false,
            "A humanoid makes a WIS save (advantage if you're fighting it) or is charmed by you until the spell ends."),
        new("Color Spray", 1, "Illusion", SW, "1 action", "Self (15-ft cone)", "V, S, M", "1 round", false, false,
            "Dazzling light blinds creatures in a 15-ft cone, starting with the lowest HP, up to a total of 6d10 HP of creatures."),
        new("Command", 1, "Enchantment", ["cleric", "paladin"], "1 action", "60 ft", "V", "1 round", false, false,
            "Speak a one-word command (Drop, Flee, Grovel, Halt...): WIS save or the creature obeys on its next turn."),
        new("Comprehend Languages", 1, "Divination", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "Self", "V, S, M", "1 hour", false, true,
            "Understand the literal meaning of any spoken or written language you hear or touch."),
        new("Cure Wounds", 1, "Evocation", ["bard", "cleric", "druid", "paladin", "ranger"], "1 action", "Touch", "V, S", "Instantaneous", false, false,
            "A touched creature regains 1d8 + your spellcasting modifier HP. +1d8 per higher slot level."),
        new("Detect Magic", 1, "Divination", ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "wizard"], "1 action", "Self", "V, S", "10 min", true, true,
            "Sense the presence of magic within 30 ft and see a faint aura around magical objects or creatures."),
        new("Disguise Self", 1, "Illusion", ["bard", "sorcerer", "wizard"], "1 action", "Self", "V, S", "1 hour", false, false,
            "Change your appearance — height (within 1 ft), weight, face, clothing. Physical inspection reveals the illusion."),
        new("Divine Favor", 1, "Evocation", PAL, "1 bonus action", "Self", "V, S", "1 min", true, false,
            "Your weapon attacks deal an extra 1d4 radiant damage."),
        new("Entangle", 1, "Conjuration", DR, "1 action", "90 ft", "V, S", "1 min", true, false,
            "Grasping plants in a 20-ft square: STR save or be restrained. A restrained creature can use its action to retry."),
        new("Faerie Fire", 1, "Evocation", ["bard", "druid"], "1 action", "60 ft", "V", "1 min", true, false,
            "Objects and creatures in a 20-ft cube glow (DEX save negates): attacks against them have advantage and they can't be invisible."),
        new("False Life", 1, "Necromancy", SW, "1 action", "Self", "V, S, M", "1 hour", false, false,
            "Gain 1d4 + 4 temporary hit points."),
        new("Feather Fall", 1, "Transmutation", ["bard", "sorcerer", "wizard"], "1 reaction", "60 ft", "V, M", "1 min", false, false,
            "Reaction when up to five creatures fall: their fall slows to 60 ft/round and they land without damage."),
        new("Find Familiar", 1, "Conjuration", ["wizard"], "1 hour", "10 ft", "V, S, M", "Instantaneous", false, true,
            "Summon a spirit familiar (cat, owl, raven...). It can scout, deliver touch spells, and grant you its senses."),
        new("Fog Cloud", 1, "Conjuration", ["druid", "ranger", "sorcerer", "wizard"], "1 action", "120 ft", "V, S", "1 hour", true, false,
            "A 20-ft-radius sphere of fog heavily obscures the area."),
        new("Goodberry", 1, "Transmutation", ["druid", "ranger"], "1 action", "Self", "V, S, M", "24 hours", false, false,
            "Create 10 berries; eating one restores 1 HP and nourishes for a day. Great out-of-combat healing."),
        new("Grease", 1, "Conjuration", ["wizard"], "1 action", "60 ft", "V, S, M", "1 min", false, false,
            "Slick grease covers a 10-ft square: creatures there or entering make a DEX save or fall prone."),
        new("Guiding Bolt", 1, "Evocation", CL, "1 action", "120 ft", "V, S", "1 round", false, false,
            "Ranged spell attack for 4d6 radiant damage; the next attack roll against the target has advantage."),
        new("Healing Word", 1, "Evocation", ["bard", "cleric", "druid"], "1 bonus action", "60 ft", "V", "Instantaneous", false, false,
            "Bonus action ranged heal: 1d4 + spellcasting modifier HP. The go-to spell for picking up downed allies."),
        new("Heroism", 1, "Enchantment", ["bard", "paladin"], "1 action", "Touch", "V, S", "1 min", true, false,
            "Touched creature is immune to being frightened and gains your spellcasting modifier in temp HP each turn."),
        new("Hunter's Mark", 1, "Divination", ["ranger"], "1 bonus action", "90 ft", "V", "1 hour", true, false,
            "Mark a creature: your weapon attacks against it deal +1d6 damage, and you have advantage to track it."),
        new("Identify", 1, "Divination", ["bard", "wizard"], "1 minute", "Touch", "V, S, M", "Instantaneous", false, true,
            "Learn the properties of a magic item or what spells affect an object or creature."),
        new("Inflict Wounds", 1, "Necromancy", CL, "1 action", "Touch", "V, S", "Instantaneous", false, false,
            "Melee spell attack for 3d10 necrotic damage. +1d10 per higher slot level."),
        new("Jump", 1, "Transmutation", ["druid", "ranger", "sorcerer", "wizard"], "1 action", "Touch", "V, S, M", "1 min", false, false,
            "Touched creature's jump distance is tripled."),
        new("Longstrider", 1, "Transmutation", ["bard", "druid", "ranger", "wizard"], "1 action", "Touch", "V, S, M", "1 hour", false, false,
            "Touched creature's speed increases by 10 ft."),
        new("Mage Armor", 1, "Abjuration", SW, "1 action", "Touch", "V, S, M", "8 hours", false, false,
            "An unarmored willing creature's base AC becomes 13 + DEX modifier. Essential for squishy casters."),
        new("Magic Missile", 1, "Evocation", SW, "1 action", "120 ft", "V, S", "Instantaneous", false, false,
            "Three darts of force automatically hit for 1d4+1 each — no attack roll, no save. +1 dart per higher slot level."),
        new("Protection from Evil and Good", 1, "Abjuration", ["cleric", "paladin", "warlock", "wizard"], "1 action", "Touch", "V, S, M", "10 min", true, false,
            "Aberrations, celestials, elementals, fey, fiends, and undead attack the target at disadvantage and can't charm/frighten/possess it."),
        new("Sanctuary", 1, "Abjuration", CL, "1 bonus action", "30 ft", "V, S, M", "1 min", false, false,
            "Creatures attacking the warded target must make a WIS save or choose a new target. Ends if the warded creature attacks."),
        new("Searing Smite", 1, "Evocation", PAL, "1 bonus action", "Self", "V", "1 min", true, false,
            "Your next melee hit deals +1d6 fire damage and ignites the target (1d6 fire/turn, CON save ends)."),
        new("Shield", 1, "Abjuration", SW, "1 reaction", "Self", "V, S", "1 round", false, false,
            "Reaction when hit: +5 AC until your next turn, possibly turning the hit into a miss. Also blocks Magic Missile."),
        new("Shield of Faith", 1, "Abjuration", ["cleric", "paladin"], "1 bonus action", "60 ft", "V, S, M", "10 min", true, false,
            "A shimmering field gives a creature +2 AC."),
        new("Silent Image", 1, "Illusion", ["bard", "sorcerer", "wizard"], "1 action", "60 ft", "V, S, M", "10 min", true, false,
            "Create a soundless image up to a 15-ft cube; you can move it. Investigation check vs your DC reveals it."),
        new("Sleep", 1, "Enchantment", ["bard", "sorcerer", "wizard"], "1 action", "90 ft", "V, S, M", "1 min", false, false,
            "Roll 5d8: that many HP of creatures fall unconscious, lowest current HP first. +2d8 per higher slot level."),
        new("Speak with Animals", 1, "Divination", ["bard", "druid", "ranger"], "1 action", "Self", "V, S", "10 min", false, true,
            "Comprehend and verbally communicate with beasts."),
        new("Tasha's Hideous Laughter", 1, "Enchantment", ["bard", "wizard"], "1 action", "30 ft", "V, S, M", "1 min", true, false,
            "Target falls prone with laughter (WIS save): incapacitated and unable to stand. Repeats save when damaged."),
        new("Thunderous Smite", 1, "Evocation", PAL, "1 bonus action", "Self", "V", "1 min", true, false,
            "Your next melee hit deals +2d6 thunder damage; STR save or the target is pushed 10 ft and knocked prone."),
        new("Thunderwave", 1, "Evocation", ["bard", "druid", "sorcerer", "wizard"], "1 action", "Self (15-ft cube)", "V, S", "Instantaneous", false, false,
            "A wave of force: CON save or take 2d8 thunder damage and be pushed 10 ft away (half damage, no push on success)."),
        new("Witch Bolt", 1, "Evocation", SWW, "1 action", "30 ft", "V, S, M", "1 min", true, false,
            "Ranged spell attack for 1d12 lightning; each later turn you can use your action to deal 1d12 automatically."),
        new("Wrathful Smite", 1, "Evocation", PAL, "1 bonus action", "Self", "V", "1 min", true, false,
            "Your next melee hit deals +1d6 psychic damage; WIS save or the target is frightened of you."),

        // ── Level 2 ──────────────────────────────────────────────────────────
        new("Aid", 2, "Abjuration", ["cleric", "paladin"], "1 action", "30 ft", "V, S, M", "8 hours", false, false,
            "Up to three creatures gain +5 maximum HP and current HP for 8 hours. +5 per higher slot level."),
        new("Alter Self", 2, "Transmutation", SW, "1 action", "Self", "V, S", "1 hour", true, false,
            "Change your appearance, grow natural weapons (1d6 + STR), or adapt to breathe underwater."),
        new("Animal Messenger", 2, "Enchantment", ["bard", "druid", "ranger"], "1 action", "30 ft", "V, S, M", "24 hours", false, true,
            "A Tiny beast delivers a short spoken message to a location you describe."),
        new("Barkskin", 2, "Transmutation", ["druid", "ranger"], "1 action", "Touch", "V, S, M", "1 hour", true, false,
            "Touched creature's AC can't be lower than 16."),
        new("Blindness/Deafness", 2, "Necromancy", ["bard", "cleric", "sorcerer", "wizard"], "1 action", "30 ft", "V", "1 min", false, false,
            "CON save or the target is blinded or deafened (your choice). Repeats save each turn."),
        new("Blur", 2, "Illusion", SW, "1 action", "Self", "V", "1 min", true, false,
            "Your body shimmers: attack rolls against you have disadvantage."),
        new("Branding Smite", 2, "Evocation", PAL, "1 bonus action", "Self", "V", "1 min", true, false,
            "Your next weapon hit deals +2d6 radiant damage and the target glows — it can't be invisible."),
        new("Calm Emotions", 2, "Enchantment", ["bard", "cleric"], "1 action", "60 ft", "V, S", "1 min", true, false,
            "Suppress charm/fear effects or make hostile humanoids in a 20-ft sphere indifferent (CHA save)."),
        new("Cloud of Daggers", 2, "Conjuration", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "60 ft", "V, S, M", "1 min", true, false,
            "Spinning daggers fill a 5-ft cube: 4d4 slashing damage to any creature entering or starting its turn there."),
        new("Crown of Madness", 2, "Enchantment", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "120 ft", "V, S", "1 min", true, false,
            "WIS save or a humanoid must attack a creature you choose each turn. Repeats save each turn."),
        new("Darkness", 2, "Evocation", SWW, "1 action", "60 ft", "V, M", "10 min", true, false,
            "Magical darkness fills a 15-ft sphere; darkvision can't see through it."),
        new("Darkvision", 2, "Transmutation", ["druid", "ranger", "sorcerer", "wizard"], "1 action", "Touch", "V, S, M", "8 hours", false, false,
            "Touched creature gains darkvision to 60 ft."),
        new("Detect Thoughts", 2, "Divination", ["bard", "sorcerer", "wizard"], "1 action", "Self", "V, S, M", "1 min", true, false,
            "Read surface thoughts of creatures within 30 ft; probe deeper with a WIS save contest."),
        new("Enhance Ability", 2, "Transmutation", ["bard", "cleric", "druid"], "1 action", "Touch", "V, S, M", "1 hour", true, false,
            "Touched creature gains advantage on checks with one ability score (plus a minor perk, e.g. Bear's Endurance: 2d6 temp HP)."),
        new("Enlarge/Reduce", 2, "Transmutation", SW, "1 action", "30 ft", "V, S, M", "1 min", true, false,
            "Double or halve a creature's size: enlarged gains +1d4 weapon damage and advantage on STR checks; reduced takes -1d4."),
        new("Find Steed", 2, "Conjuration", PAL, "10 minutes", "30 ft", "V, S", "Instantaneous", false, false,
            "Summon a loyal spirit steed (warhorse, pony, elk...) that you can communicate with telepathically."),
        new("Flame Blade", 2, "Evocation", DR, "1 bonus action", "Self", "V, S, M", "10 min", true, false,
            "A fiery scimitar appears in your hand: melee spell attack for 3d6 fire damage."),
        new("Flaming Sphere", 2, "Conjuration", ["druid", "wizard"], "1 action", "60 ft", "V, S, M", "1 min", true, false,
            "A 5-ft ball of fire you can move 30 ft as a bonus action: creatures within 5 ft make a DEX save or take 2d6 fire."),
        new("Gust of Wind", 2, "Evocation", ["druid", "sorcerer", "wizard"], "1 action", "Self (60-ft line)", "V, S, M", "1 min", true, false,
            "A 60-ft line of wind pushes creatures 15 ft away (STR save) and halves movement toward you."),
        new("Heat Metal", 2, "Transmutation", ["bard", "druid"], "1 action", "60 ft", "V, S, M", "1 min", true, false,
            "A metal object glows red-hot: 2d8 fire damage to whoever holds/wears it, repeatable each turn as a bonus action. No save to resist the damage!"),
        new("Hold Person", 2, "Enchantment", ["bard", "cleric", "druid", "sorcerer", "warlock", "wizard"], "1 action", "60 ft", "V, S, M", "1 min", true, false,
            "WIS save or a humanoid is paralyzed. Attacks within 5 ft auto-crit a paralyzed target. Repeats save each turn."),
        new("Invisibility", 2, "Illusion", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "Touch", "V, S, M", "1 hour", true, false,
            "Touched creature is invisible until it attacks or casts a spell."),
        new("Knock", 2, "Transmutation", ["bard", "sorcerer", "wizard"], "1 action", "60 ft", "V", "Instantaneous", false, false,
            "Open a locked door, chest, or shackles — with a loud knock audible 300 ft away."),
        new("Lesser Restoration", 2, "Abjuration", ["bard", "cleric", "druid", "paladin", "ranger"], "1 action", "Touch", "V, S", "Instantaneous", false, false,
            "End one disease or condition (blinded, deafened, paralyzed, or poisoned) on a touched creature."),
        new("Levitate", 2, "Transmutation", SW, "1 action", "60 ft", "V, S, M", "10 min", true, false,
            "A creature or object rises vertically up to 20 ft (CON save for unwilling targets)."),
        new("Locate Object", 2, "Divination", ["bard", "cleric", "druid", "paladin", "ranger", "wizard"], "1 action", "Self", "V, S, M", "10 min", true, false,
            "Sense the direction to a familiar object within 1,000 ft."),
        new("Magic Weapon", 2, "Transmutation", ["paladin", "wizard"], "1 bonus action", "Touch", "V, S", "1 hour", true, false,
            "A nonmagical weapon becomes a +1 magic weapon."),
        new("Mirror Image", 2, "Illusion", SWW, "1 action", "Self", "V, S", "1 min", false, false,
            "Three illusory duplicates of you appear; attacks may hit a duplicate (destroying it) instead of you."),
        new("Misty Step", 2, "Conjuration", SWW, "1 bonus action", "Self", "V", "Instantaneous", false, false,
            "Teleport up to 30 ft to a spot you can see — as a bonus action. Premier escape spell."),
        new("Moonbeam", 2, "Evocation", DR, "1 action", "120 ft", "V, S, M", "1 min", true, false,
            "A 5-ft-radius beam of pale light: CON save or take 2d10 radiant damage; move it 60 ft each turn as an action."),
        new("Pass without Trace", 2, "Abjuration", ["druid", "ranger"], "1 action", "Self", "V, S, M", "1 hour", true, false,
            "You and companions within 30 ft gain +10 to Stealth checks and can't be tracked. The party-stealth spell."),
        new("Prayer of Healing", 2, "Evocation", CL, "10 minutes", "30 ft", "V", "Instantaneous", false, false,
            "Up to six creatures regain 2d8 + spellcasting modifier HP."),
        new("Protection from Poison", 2, "Abjuration", ["cleric", "druid", "paladin", "ranger"], "1 action", "Touch", "V, S", "1 hour", false, false,
            "Neutralize one poison; target has advantage on saves vs poison and resistance to poison damage."),
        new("Scorching Ray", 2, "Evocation", SW, "1 action", "120 ft", "V, S", "Instantaneous", false, false,
            "Three rays of fire: ranged spell attack each, 2d6 fire damage per hit. +1 ray per higher slot level."),
        new("See Invisibility", 2, "Divination", ["bard", "sorcerer", "wizard"], "1 action", "Self", "V, S, M", "1 hour", false, false,
            "See invisible creatures and objects, and into the Ethereal Plane."),
        new("Shatter", 2, "Evocation", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "60 ft", "V, S, M", "Instantaneous", false, false,
            "A painful ringing in a 10-ft sphere: CON save or take 3d8 thunder damage. Great vs groups and objects."),
        new("Silence", 2, "Illusion", ["bard", "cleric", "ranger"], "1 action", "120 ft", "V, S", "10 min", true, true,
            "No sound within a 20-ft sphere: blocks verbal spellcasting and thunder damage. Shuts down enemy casters."),
        new("Spider Climb", 2, "Transmutation", SWW, "1 action", "Touch", "V, S, M", "1 hour", true, false,
            "Touched creature walks on walls and ceilings with hands free."),
        new("Spike Growth", 2, "Transmutation", ["druid", "ranger"], "1 action", "150 ft", "V, S, M", "10 min", true, false,
            "A 20-ft radius becomes hidden spikes: 2d4 piercing damage per 5 ft moved through it."),
        new("Spiritual Weapon", 2, "Evocation", CL, "1 bonus action", "60 ft", "V, S", "1 min", false, false,
            "A floating spectral weapon attacks as your bonus action: 1d8 + spellcasting modifier force damage. No concentration!"),
        new("Suggestion", 2, "Enchantment", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "30 ft", "V, M", "8 hours", true, false,
            "Suggest a reasonable-sounding course of action: WIS save or the creature pursues it for up to 8 hours."),
        new("Web", 2, "Conjuration", SW, "1 action", "60 ft", "V, S, M", "1 hour", true, false,
            "Thick webs fill a 20-ft cube: DEX save or be restrained (STR check to escape). Flammable."),
        new("Zone of Truth", 2, "Enchantment", ["bard", "cleric", "paladin"], "1 action", "60 ft", "V, S", "10 min", false, false,
            "Creatures in a 15-ft sphere can't deliberately lie (CHA save negates; you know who failed)."),

        // ── Level 3 ──────────────────────────────────────────────────────────
        new("Aura of Vitality", 3, "Evocation", PAL, "1 action", "Self (30-ft radius)", "V", "1 min", true, false,
            "Healing aura: each turn, use a bonus action to heal one creature in range for 2d6 HP. Up to 20d6 total healing!"),
        new("Beacon of Hope", 3, "Abjuration", CL, "1 action", "30 ft", "V, S", "1 min", true, false,
            "Chosen creatures have advantage on WIS and death saves, and regain maximum HP from healing."),
        new("Bestow Curse", 3, "Necromancy", ["bard", "cleric", "wizard"], "1 action", "Touch", "V, S", "1 min", true, false,
            "WIS save or curse the target: disadvantage with one ability, disadvantage vs your attacks, +1d8 necrotic from your attacks, or waste turns."),
        new("Blinding Smite", 3, "Evocation", PAL, "1 bonus action", "Self", "V", "1 min", true, false,
            "Your next melee hit deals +3d8 radiant damage; CON save or the target is blinded."),
        new("Call Lightning", 3, "Conjuration", DR, "1 action", "120 ft", "V, S", "10 min", true, false,
            "A storm cloud: call a bolt each turn as an action — DEX save or 3d10 lightning damage in a 5-ft radius."),
        new("Conjure Animals", 3, "Conjuration", ["druid", "ranger"], "1 action", "60 ft", "V, S", "1 hour", true, false,
            "Summon fey beasts: e.g. eight wolves of CR 1/4. They act on their own turn and obey your commands."),
        new("Counterspell", 3, "Abjuration", SWW, "1 reaction", "60 ft", "S", "Instantaneous", false, false,
            "Reaction to interrupt a spell being cast: auto-negates 3rd level or lower; ability check for higher."),
        new("Crusader's Mantle", 3, "Evocation", PAL, "1 action", "Self (30-ft radius)", "V", "1 min", true, false,
            "Allies in your aura deal +1d4 radiant damage on weapon attacks."),
        new("Daylight", 3, "Evocation", ["cleric", "druid", "paladin", "ranger", "sorcerer"], "1 action", "60 ft", "V, S", "1 hour", false, false,
            "A 60-ft sphere of bright sunlight-like radiance; dispels magical darkness of 3rd level or lower."),
        new("Dispel Magic", 3, "Abjuration", ["bard", "cleric", "druid", "paladin", "sorcerer", "warlock", "wizard"], "1 action", "120 ft", "V, S", "Instantaneous", false, false,
            "End spells of 3rd level or lower on a target (ability check for higher-level effects)."),
        new("Fear", 3, "Illusion", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "Self (30-ft cone)", "V, S, M", "1 min", true, false,
            "Creatures in a 30-ft cone see their worst fear: WIS save or drop what they hold and become frightened, fleeing from you."),
        new("Fireball", 3, "Evocation", SW, "1 action", "150 ft", "V, S, M", "Instantaneous", false, false,
            "The classic: a 20-ft-radius explosion, DEX save or take 8d6 fire damage (half on success). +1d6 per higher slot."),
        new("Fly", 3, "Transmutation", SWW, "1 action", "Touch", "V, S, M", "10 min", true, false,
            "Touched creature gains a 60-ft flying speed."),
        new("Gaseous Form", 3, "Transmutation", SWW, "1 action", "Touch", "V, S, M", "1 hour", true, false,
            "Touched creature becomes a misty cloud: fly 10 ft, fit through cracks, resistance to nonmagical damage."),
        new("Haste", 3, "Transmutation", SW, "1 action", "30 ft", "V, S, M", "1 min", true, false,
            "Target gains +2 AC, advantage on DEX saves, doubled speed, and an extra action each turn. Lethargy when it ends."),
        new("Hypnotic Pattern", 3, "Illusion", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "120 ft", "S, M", "1 min", true, false,
            "Twisting colors in a 30-ft cube: WIS save or be charmed and incapacitated until shaken awake. Encounter-ender."),
        new("Lightning Bolt", 3, "Evocation", SW, "1 action", "Self (100-ft line)", "V, S, M", "Instantaneous", false, false,
            "A 100-ft line of lightning: DEX save or take 8d6 lightning damage (half on success)."),
        new("Major Image", 3, "Illusion", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "120 ft", "V, S, M", "10 min", true, false,
            "A full sensory illusion up to a 20-ft cube — sight, sound, smell, and temperature."),
        new("Mass Healing Word", 3, "Evocation", CL, "1 bonus action", "60 ft", "V", "Instantaneous", false, false,
            "Bonus action: up to six creatures regain 1d4 + spellcasting modifier HP."),
        new("Plant Growth", 3, "Transmutation", ["bard", "druid", "ranger"], "1 action", "150 ft", "V, S", "Instantaneous", false, false,
            "Overgrow a 100-ft radius (quadruple movement cost) or enrich land for a year of bountiful harvest."),
        new("Protection from Energy", 3, "Abjuration", ["cleric", "druid", "ranger", "sorcerer", "wizard"], "1 action", "Touch", "V, S", "1 hour", true, false,
            "Touched creature gains resistance to acid, cold, fire, lightning, or thunder damage."),
        new("Revivify", 3, "Necromancy", ["cleric", "paladin"], "1 action", "Touch", "V, S, M", "Instantaneous", false, false,
            "Return a creature dead less than a minute to life with 1 HP. Requires 300 gp of diamonds. Keep diamonds in your pack!"),
        new("Sleet Storm", 3, "Conjuration", ["druid", "sorcerer", "wizard"], "1 action", "150 ft", "V, S, M", "1 min", true, false,
            "Freezing rain in a 40-ft radius: heavily obscured, DEX save or fall prone, concentration checks to maintain spells."),
        new("Slow", 3, "Transmutation", SW, "1 action", "120 ft", "V, S, M", "1 min", true, false,
            "Up to six creatures: WIS save or halved speed, -2 AC and DEX saves, no reactions, and only one attack per turn."),
        new("Speak with Dead", 3, "Necromancy", ["bard", "cleric"], "1 action", "10 ft", "V, S, M", "10 min", false, false,
            "Ask a corpse five questions. It knows only what it knew in life and can be evasive."),
        new("Spirit Guardians", 3, "Conjuration", CL, "1 action", "Self (15-ft radius)", "V, S, M", "10 min", true, false,
            "Protective spirits swirl around you: enemies entering take 3d8 radiant/necrotic (WIS save halves) and are slowed."),
        new("Stinking Cloud", 3, "Conjuration", ["bard", "sorcerer", "wizard"], "1 action", "90 ft", "V, S, M", "1 min", true, false,
            "Nauseating gas in a 20-ft sphere: CON save or spend your action retching."),
        new("Tongues", 3, "Divination", ["bard", "cleric", "sorcerer", "warlock", "wizard"], "1 action", "Touch", "V, M", "1 hour", false, false,
            "Touched creature understands and is understood by any spoken language."),
        new("Vampiric Touch", 3, "Necromancy", ["warlock", "wizard"], "1 action", "Self", "V, S", "1 min", true, false,
            "Melee spell attack for 3d6 necrotic; you heal half the damage dealt."),
        new("Water Breathing", 3, "Transmutation", ["druid", "ranger", "sorcerer", "wizard"], "1 action", "30 ft", "V, S, M", "24 hours", false, true,
            "Up to ten creatures can breathe underwater for 24 hours."),
        new("Water Walk", 3, "Transmutation", ["cleric", "druid", "ranger", "sorcerer"], "1 action", "30 ft", "V, S, M", "1 hour", false, true,
            "Up to ten creatures walk on liquid surfaces."),
        new("Wind Wall", 3, "Evocation", ["druid", "ranger"], "1 action", "120 ft", "V, S, M", "1 min", true, false,
            "A wall of strong wind: 3d8 bludgeoning (STR save), blocks arrows, gas, and flying creatures."),

        // ── Level 4 ──────────────────────────────────────────────────────────
        new("Banishment", 4, "Abjuration", ["cleric", "paladin", "sorcerer", "warlock", "wizard"], "1 action", "60 ft", "V, S, M", "1 min", true, false,
            "CHA save or the target is banished to another plane; if it's extraplanar and you hold concentration 1 minute, it doesn't return."),
        new("Blight", 4, "Necromancy", ["druid", "sorcerer", "warlock", "wizard"], "1 action", "30 ft", "V, S", "Instantaneous", false, false,
            "Necromantic energy: CON save or take 8d8 necrotic damage. Devastating vs plants."),
        new("Confusion", 4, "Enchantment", ["bard", "druid", "sorcerer", "wizard"], "1 action", "90 ft", "V, S, M", "1 min", true, false,
            "Creatures in a 10-ft sphere: WIS save or act randomly — wander, babble, or attack the nearest creature."),
        new("Death Ward", 4, "Abjuration", ["cleric", "paladin"], "1 action", "Touch", "V, S", "8 hours", false, false,
            "The first time the target would drop to 0 HP, it drops to 1 HP instead."),
        new("Dimension Door", 4, "Conjuration", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "500 ft", "V", "Instantaneous", false, false,
            "Teleport yourself (and one willing creature) up to 500 ft to a spot you can see, visualize, or describe."),
        new("Dominate Beast", 4, "Enchantment", ["druid", "sorcerer"], "1 action", "60 ft", "V, S", "1 min", true, false,
            "WIS save or a beast obeys your telepathic commands. Repeats save when damaged."),
        new("Freedom of Movement", 4, "Abjuration", ["bard", "cleric", "druid", "ranger"], "1 action", "Touch", "V, S, M", "1 hour", false, false,
            "Target ignores difficult terrain; magic can't reduce its speed, paralyze, or restrain it."),
        new("Greater Invisibility", 4, "Illusion", ["bard", "sorcerer", "wizard"], "1 action", "Touch", "V, S", "1 min", true, false,
            "Touched creature is invisible — even while attacking or casting."),
        new("Guardian of Faith", 4, "Conjuration", CL, "1 action", "30 ft", "V", "8 hours", false, false,
            "A spectral guardian: enemies within 10 ft make a DEX save or take 20 radiant damage. Lasts until it deals 60 damage."),
        new("Ice Storm", 4, "Evocation", ["druid", "sorcerer", "wizard"], "1 action", "300 ft", "V, S, M", "Instantaneous", false, false,
            "Hail in a 20-ft cylinder: DEX save or 2d8 bludgeoning + 4d6 cold; ground is difficult terrain until next turn."),
        new("Polymorph", 4, "Transmutation", ["bard", "druid", "sorcerer", "wizard"], "1 action", "60 ft", "V, S, M", "1 hour", true, false,
            "Transform a creature into a beast (WIS save if unwilling). Turn an ally into a giant ape — or a boss into a turtle."),
        new("Stoneskin", 4, "Abjuration", ["druid", "ranger", "sorcerer", "wizard"], "1 action", "Touch", "V, S, M", "1 hour", true, false,
            "Touched creature has resistance to nonmagical bludgeoning, piercing, and slashing damage."),
        new("Wall of Fire", 4, "Evocation", ["druid", "sorcerer", "wizard"], "1 action", "120 ft", "V, S, M", "1 min", true, false,
            "A 60-ft wall of flame: 5d8 fire damage (DEX save) to creatures in or beside it when it appears, and each turn within it."),

        // ── Level 5 ──────────────────────────────────────────────────────────
        new("Animate Objects", 5, "Transmutation", ["bard", "sorcerer", "wizard"], "1 action", "120 ft", "V, S", "1 min", true, false,
            "Up to ten objects come to life and attack — ten tiny objects deal 1d4+4 each as a swarm of +8 attacks."),
        new("Cloudkill", 5, "Conjuration", ["sorcerer", "wizard"], "1 action", "120 ft", "V, S", "10 min", true, false,
            "A 20-ft sphere of poison fog that creeps along the ground: CON save or 5d8 poison damage each turn."),
        new("Commune", 5, "Divination", CL, "1 minute", "Self", "V, S, M", "1 min", false, true,
            "Ask your deity three yes/no questions."),
        new("Cone of Cold", 5, "Evocation", SW, "1 action", "Self (60-ft cone)", "V, S, M", "Instantaneous", false, false,
            "A 60-ft cone of frost: CON save or take 8d8 cold damage (half on success)."),
        new("Dominate Person", 5, "Enchantment", ["bard", "sorcerer", "wizard"], "1 action", "60 ft", "V, S", "1 min", true, false,
            "WIS save or a humanoid obeys your telepathic commands; take total control with your action."),
        new("Flame Strike", 5, "Evocation", CL, "1 action", "60 ft", "V, S, M", "Instantaneous", false, false,
            "A divine column of fire: DEX save or 4d6 fire + 4d6 radiant damage in a 10-ft cylinder."),
        new("Greater Restoration", 5, "Abjuration", ["bard", "cleric", "druid"], "1 action", "Touch", "V, S, M", "Instantaneous", false, false,
            "End one: charm, petrification, curse, ability score reduction, or max HP reduction."),
        new("Hold Monster", 5, "Enchantment", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "90 ft", "V, S, M", "1 min", true, false,
            "Like Hold Person but works on any creature: WIS save or paralyzed. Melee hits auto-crit."),
        new("Mass Cure Wounds", 5, "Evocation", ["bard", "cleric", "druid"], "1 action", "60 ft", "V, S", "Instantaneous", false, false,
            "Up to six creatures in a 30-ft sphere regain 3d8 + spellcasting modifier HP."),
        new("Raise Dead", 5, "Necromancy", ["bard", "cleric", "paladin"], "1 hour", "Touch", "V, S, M", "Instantaneous", false, false,
            "Return a creature dead up to 10 days to life. Requires a 500 gp diamond."),
        new("Telekinesis", 5, "Transmutation", ["sorcerer", "wizard"], "1 action", "60 ft", "V, S", "10 min", true, false,
            "Move a creature (STR contest) or 1,000 lb object 30 ft with your mind each turn."),
        new("Wall of Stone", 5, "Transmutation", ["druid", "sorcerer", "wizard"], "1 action", "120 ft", "V, S, M", "10 min", true, false,
            "Create a stone wall of ten 10-ft panels. Concentrate the full duration and it becomes permanent."),

        // ── From the party's PDF sheets (source-tagged) ──────────────────────
        new("Friends", 0, "Enchantment", ["bard", "sorcerer", "warlock", "wizard"], "1 action", "10 ft", "S, M", "1 min", true, false,
            "You gain Advantage on Charisma checks against one creature that isn't hostile. When the spell ends, the creature realizes you used magic to influence it and may become hostile."),
        new("Elementalism", 0, "Transmutation", ["druid", "sorcerer", "wizard"], "1 action", "30 ft", "V, S", "Instantaneous", false, false,
            "Manipulate the elements for a minor effect: douse or ignite a small flame, make a 5-ft cube of mist/mud/dust, or send a harmless gust. (One option per casting.)"),
        new("Sorcerous Burst", 0, "Evocation", SW, "1 action", "120 ft", "V, S", "Instantaneous", false, false,
            "Ranged spell attack: 1d8 damage of a type you choose (acid, cold, fire, lightning, poison, psychic, or thunder). If you roll an 8 on a die, roll another d8 and add it (repeatable). Scales at levels 5/11/17.",
            "PHB 2024"),
        new("Aganazzar's Scorcher", 2, "Evocation", SW, "1 action", "Self (30-ft line)", "V, S, M", "Instantaneous", false, false,
            "A line of roaring flame 30 ft long and 5 ft wide. Each creature in the line makes a DEX save, taking 3d8 fire damage on a fail (half on success). +1d8 per slot above 2nd.",
            "Elemental Evil"),
        new("Dragon's Breath", 2, "Transmutation", SW, "1 bonus action", "Touch", "V, S, M", "1 min", true, false,
            "Touch a willing creature; until the spell ends it can use an action to exhale a 15-ft cone of acid, cold, fire, lightning, or poison (chosen when cast). DEX save or 3d6 damage (half on success). +1d6 per slot above 2nd.",
            "Xanathar's Guide"),

        // ── Filling subclass-granted gaps ────────────────────────────────────
        new("Arms of Hadar", 1, "Conjuration", ["warlock", "sorcerer"], "1 action", "Self (10-ft radius)", "V, S", "Instantaneous", false, false,
            "Tendrils of dark energy erupt from you: each creature in a 10-ft radius makes a STR save, taking 2d6 necrotic on a fail (half on success) and being unable to take reactions until its next turn. +1d6 per slot above 1st."),
        new("Hunger of Hadar", 3, "Conjuration", ["warlock", "sorcerer"], "1 action", "150 ft", "V, S, M", "1 min", true, false,
            "Open a 20-ft sphere of cold void. A creature starting its turn there takes 2d6 cold; a creature ending its turn there makes a DEX save or takes 2d6 acid. The area is Darkness and difficult terrain."),
        new("Sending", 3, "Divination", ["bard", "cleric", "wizard", "sorcerer"], "1 action", "Unlimited", "V, S, M", "1 round", false, false,
            "Send a short message of 25 words or less to a creature you're familiar with, anywhere on the same plane; it can reply in kind."),
        new("Hellish Rebuke", 1, "Evocation", ["warlock", "sorcerer", "paladin"], "1 reaction", "60 ft", "V, S", "Instantaneous", false, false,
            "Reaction when a creature you can see damages you: it makes a DEX save, taking 2d10 fire on a fail (half on success). +1d10 per slot above 1st."),
    ];
}
